name: userapp
publish_to: 'none'

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    path: data
  domain:
    path: domain
  flutter_bloc: ^8.0.1 

dev_dependencies:
  flutter_lints: ^1.0.0
  dart_code_metrics: ^4.14.0

flutter:
  uses-material-design: true
